service:
  name: auction-service

plugins:
  - serverless-bundle #Allows us to bundle our application using webpack
  - serverless-pseudo-parameters #Allows us to easily interpolate AWS parameters such as origin and a country

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: 'sa-east-1'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/AuctionsTable
resources:
  Resources:
    AuctionsTable: #Logical Id for a resource
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:         #It's an array of objects representing the attributes that must be in each item of our table
          - AttributeName: id
            AttributeType: S          #S stands for 'string'
        KeySchema:                    
          - AttributeName: id # We define that the attribute id is the partition key of the table
            KeyType: HASH
  
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
